### ISSUE TITLE
Invalid credentials for payment gateway are hidden

### ISSUE THREAD

**Issue by hailwood** [silverstripe/silverstripe-omnipay#140] opened 2016-08-15 07:36 UTC
If you get an error response back from the payment gateway (currently testing with payment express hosted but envision this is the same case on any offsite payment providers) on the initial transaction request such as invalid credentials the actual error message is hidden as it doesn't throw an exception so gets treated as a successful response.

This in turn means that by the time we actually get to see an error it's the rather unhelpful "cannot redirect to an empty url" message, you need to xdebug trace through to actually find the error.

I'm not entirely sure if this one should be logged here or against the league package but since I've been logging a couple here thought I might as well see what we have to say.

**Comment by bummzack** [comment] 2016-08-15 08:30
Yeah, others have stumbled across this as well… 
The problem is, that there's no way to see if there was an error from the outside… an Omnipay Redirect Response will always have `isSuccessful === false` and `isRedirect === true`. 

What's really strange is that PxPay itself seems to return `valid=1` with their XML, even when the request was clearly invalid: http://www.paymentexpress.com/developer-e-commerce-paymentexpress-hosted-pxpay#request_response_codes

Ideally, this would be handled within the PxPay gateway, throwing an error with the XML message when there's no redirect URL coming back. Or simply return `false` with the `isRedirect` method if there's no redirect URL…

Both of the above could help detect error-responses from PxPay.

**Comment by bummzack** [comment] 2016-09-15 06:25
@hailwood Have you raised this issue over at the league PxPay driver? I think it would be worth fixing there.

**Comment by hailwood** [comment] 2016-09-15 21:15
Hey @bummzack,

I seem to have missed your initial response, so nope no issue logged.
You're obviously more familiar with the internals of the driver once it gets outside of this package however so perhaps you'd be better placed than me to log the issue over at League?

**Comment by bummzack** [comment] 2016-09-19 08:13
It seems like this is already fixed, just not in an official release yet: https://github.com/thephpleague/omnipay-paymentexpress/pull/32

Using the master branch of the omnipay driver should solve the issue.

@hailwood I guess we can close this issue?

**Comment by hailwood** [comment] 2016-09-19 08:23
@bummzack Yeah, closed issues are searchable so it makes no difference whether it's closed or open until that's merged.

Perhaps just keep this issue in mind and comment a bit later once it is merged in upstream though - I hate coming across issues and not knowing whether the thing they were waiting on was merged in between now and then!

**Comment by bummzack** [comment] 2016-09-19 08:35
You're right. I'll leave it open for now. Until there's a new release for pxpay that officially solves this,

**Comment by bummzack** [comment] 2017-06-22 06:35
This is fixed with the latest release (2.2.1) of the paymentexpress driver.

**Closed by bummzack** 2017-06-22 06:35 UTC
Labels: gateway-specific
